### ISSUE TITLE
Regarding the script execution error in `unconditional layout generation`

### ISSUE THREAD

**Issue by shunk031** [mayu-ot/ltsim#2]
Hi, thank you for releasing such an excellent evaluation metric for layout generation!

I followed [the instructions in the README](https://github.com/mayu-ot/ltsim?tab=readme-ov-file#evaluate-unconditional-layout-generation) to run the evaluation script, but I encountered the following error. 

```
⬢ [Docker] ❯ poetry run python src/experiments/eval_unconditional.py rico output_results_rico
data/fid_feat/results_unconditional/rico/layoutdm/seed_0_run_0.npy
data/fid_feat/results_unconditional/rico/layoutdm/seed_1_run_0.npy
data/fid_feat/results_unconditional/rico/layoutdm/seed_2_run_0.npy
data/fid_feat/results_unconditional/rico/vqdiffusion/seed_0_run_0.npy
data/fid_feat/results_unconditional/rico/vqdiffusion/seed_1_run_0.npy
data/fid_feat/results_unconditional/rico/vqdiffusion/seed_2_run_0.npy
data/fid_feat/results_unconditional/rico/bart/seed_0_run_0.npy
data/fid_feat/results_unconditional/rico/bart/seed_1_run_0.npy
data/fid_feat/results_unconditional/rico/bart/seed_2_run_0.npy
data/fid_feat/results_unconditional/rico/maskgit/seed_0_run_0.npy
data/fid_feat/results_unconditional/rico/maskgit/seed_1_run_0.npy
data/fid_feat/results_unconditional/rico/maskgit/seed_2_run_0.npy
data/fid_feat/results_unconditional/rico/blt/seed_0_run_0.npy
data/fid_feat/results_unconditional/rico/blt/seed_1_run_0.npy
data/fid_feat/results_unconditional/rico/blt/seed_2_run_0.npy
Traceback (most recent call last):
  File "/root/ghq/github.com/creative-graphic-design/ltsim/src/experiments/eval_unconditional.py", line 122, in <module>
    run()
    ~~~^^
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/ghq/github.com/creative-graphic-design/ltsim/src/experiments/eval_unconditional.py", line 110, in run
    mmd_result = get_mmd_result(emd_dir, yy_file)
  File "/root/ghq/github.com/creative-graphic-design/ltsim/src/experiments/eval_unconditional.py", line 41, in get_mmd_result
    emd_yy = csvfile_to_array(yy_file)
  File "/root/ghq/github.com/creative-graphic-design/ltsim/src/experiments/utils.py", line 92, in csvfile_to_array
    df = pd.read_csv(
        file,
        header=None,
        names=["i", "j", "value"],
    )
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ~~~~~~~~~~^
        f,
        ^^
    ...<6 lines>...
        storage_options=self.options.get("storage_options", None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/ghq/github.com/creative-graphic-design/ltsim/.venv/lib/python3.13/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
FileNotFoundError: [Errno 2] No such file or directory: 'data/dataflow/outputs/datasets/rico25/test_yy.csv'
```

It seems that the instruction did not mention `data/dataflow/outputs/datasets/rico25/test_yy.csv`. Could you provide information about this file?

**Comment by mayu-ot** [comment]
Thank you for your interest in this project.
I apologize for the late response as I was on leave.
As you pointed out, the description of test_yy.csv was missing.
test_yy.csv is a file that contains the similarity within the real layout set. It is to be calculated using the scripts in [ltsim/dataflow](https://github.com/mayu-ot/ltsim/tree/main/dataflow).
Since I have just returned to work, it might take some time to reflect the changes, so if you are okay with the results file used in the paper, I can share it with you.
If you need the file  immediately, could you please contact me via email?

**Comment by shunk031** [comment]
Hi @mayu-ot san, thank you for your response. 

If possible, uploading the processed files to a cloud service like Google Drive could positively impact subsequent research efforts. I would appreciate hearing your thoughts on this suggestion 🙇
